# Generated by Django 5.1.2 on 2024-11-30 22:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('dt_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interessado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ocupacao', models.CharField(max_length=255)),
                ('vdm', models.CharField(choices=[('acesso', 'Acesso'), ('outro', 'Outro')], max_length=100)),
                ('kilometragem', models.DecimalField(decimal_places=2, default='0.0', max_digits=10)),
                ('nome_br', models.CharField(max_length=255)),
                ('sentido', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255,null=True)),
                ('estado', models.CharField(max_length=255,null=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_folha', models.CharField(blank=True, max_length=20, null=True)),
                ('responsavel_tecnico', models.CharField(max_length=255)),
                ('descricao_processo', models.TextField()),
                ('data_recebimento', models.CharField(blank=True, max_length=20, null=True)),
                ('data_devolucao', models.CharField(blank=True, max_length=20, null=True)),
                ('data_hora_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tb_interessado',
            },
        ),
        migrations.CreateModel(
            name='PdfValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.TextField(blank=True, null=True)),
                ('etapa', models.CharField(blank=True, max_length=255, null=True)),
                ('projeto', models.CharField(blank=True, max_length=255, null=True)),
                ('proprietario_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('responsavel_tecnico', models.CharField(blank=True, max_length=255, null=True)),
                ('prancha', models.CharField(blank=True, max_length=10, null=True)),
                ('data_hora_cadastro', models.DateTimeField(auto_now_add=True)),
                ('interessado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_validations', to='accounts.interessado')),
            ],
            options={
                'db_table': 'tb_pdf_validation',
            },
        ),
    ]
